### ISSUE TITLE
api key

### ISSUE THREAD

**Issue by GarrettRector** [Jman4190/gpt3-jabebot#1]
lmao I saw ur article because im trying to get gpt3 to work for me too, so I went and looked at ur repo, and your key is showing in ur code bro. Im not gonna use it but I'd take that down if I were you

**Comment by Jman4190** [comment]
So kind of you to reach out as I'm sure tons of people tried to use it. I regenerated the key a long time ago but will replace it now so further folks don't get disappointed when it doesn't work :)
